classDiagram
    class Person {
        -int personID
        -string fornavn
        -string etternavn
        -string telefonnummer
    }

    class Innmelder {
        -int innmelderID
        -string epost
        -InnmelderType innmelderType
    }

    class Saksbehandler {
        -int saksbehandlerID
        -string jobbepost
        -string jobbtelefon
        -Stilling stilling
    }

    class GjesteInnmelder {
        -int gjestInnmelderID
        -string epost
    }

    class Innmelding {
        -int innmeldingID
        -string tittel
        -string beskrivelse
        -datetime innmeldingstidspunkt
        -Status status
        -datetime sisteEndring
        -Prioritet prioritet
        -KartType kartType
    }

    class Geometri {
        -int geometriID
        -string geometriData
    }

    class Tilbakemelding {
        -int tilbakemeldingsID
        -datetime dato
        -string innhold
    }

    Person <|-- Innmelder
    Person <|-- Saksbehandler
    Innmelder "1" -- "*" Innmelding : lager
    GjesteInnmelder "1" -- "*" Innmelding : lager
    Saksbehandler "1" -- "*" Innmelding : behandler
    Innmelding "1" -- "*" Geometri : har
    Innmelding "1" -- "*" Tilbakemelding : mottar
    Saksbehandler "1" -- "*" Tilbakemelding : skriver